stackPrefix: sample-app-
variables:
  bucketName: molnarbence-sample-storage
  project: SampleProject

stackTags:
  Contact: myemail@example.com
  Project: ${variables.project}

stacks:
  - name: iam-role
    template: templates/iam-role.yml
    parameters:
      RoleName: sample-app-role
      BucketName: ${variables.bucketName}
      Project: ${variables.project}
  - name: bucket
    template: templates/bucket.yml
    parameters:
      BucketName: molnarbence-sample-storage
      RoleARN: ${outputs.iam-role.RoleARN}
      Project: ${variables.project}
  